### ISSUE TITLE
Does not work properly with tsconfig path aliases

### ISSUE THREAD

**Issue by DanteDeRuwe** [Al3xCubed/annotation-lens-cubed#4]
Hi. I really like your extension. It's one that I've been looking for and was wondering why VSCode does not have it by default. Great job!

I've found an issue while working in a rather big Angular project. We have common code that lives in a `common` folder. Rather than doing `import from '../../../../../common'` (1), we use `import from '@common'` (2). 

When importing a base class using (2), and extending it, the codelenses are not visible.

These path aliases are defined in `tsconfig.json`. Could you add a way to resolve these to add support for these kinds of imports? Or maybe with some guidance I can open a PR myself.

Thanks!

**Comment by Al3xCubed** [comment]
Hi! Thank you for using my extension, it's great to hear that you find it useful.

As for the bug, I have indeed used path alises in other projects before too and it should definitely work for those too. I'll try to see what I can do and I'll keep you updated here.

**Comment by Al3xCubed** [comment]
After I made a quick test using path aliases, it seems to work just fine: 
![image](https://user-images.githubusercontent.com/45522435/139909417-7dbdc9a4-bdce-4c65-bf03-5ceb3e51c924.png)
![image](https://user-images.githubusercontent.com/45522435/139909389-8e30c2e3-0e5c-4d1b-ab76-5cd3aa5c22b4.png)

So I think something else might be going wrong. Could you maybe provide a small project repo that reproduces the issue, that would help identifying the issue.

**Comment by DanteDeRuwe** [comment]
I cannot seem to reproduce the issue myself, so I will close this issue for now. If I get an idea of what it might be I will reopen. Thanks for the swift response! 🍻
